services:
  postgres:
    image: postgres:16-alpine
    container_name: 4stepsvpn-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: 4stepsvpn
      POSTGRES_PASSWORD: 4stepsvpn
      POSTGRES_DB: 4stepsvpn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: 4stepsvpn-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
