# 4StepsVPN rate limiting

# Normal WebApp API requests.
limit_req_zone $binary_remote_addr
    zone=4steps_webapp:10m
    rate=10r/s;

# Sensitive state-changing operations.
limit_req_zone $binary_remote_addr
    zone=4steps_write:10m
    rate=2r/s;
